DevCard_Mvc/Models/Article.cs
namespace DevCard_Mvc.Models
{
    public class Article
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }


        public Article(long id, string title, string description, string image)
        {
	        Id = id;
	        Title = title;
	        Description = description;
	        Image = image;
        }
    }
}

DevCard_Mvc/Models/Contact.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DevCard_Mvc.Models
{
    public class Contact
    {
        [Required(ErrorMessage = "این فیلد اجباری است")]
        [MinLength(3,ErrorMessage = "حداقل طول نام 3 کاراکتر است")]
       [MaxLength(100,ErrorMessage = "حداکثر طول نام 100 کاراکتر است")]
        public string Name { get; set; }
        [Required(ErrorMessage = "این فیلد اجباری است")]
        [EmailAddress(ErrorMessage = "مفدار وارد شده صحیح نمی باشد")]
        public string Email { get; set; }
        public string Message { get; set; }  
        public  int Service { get; set; }
        public SelectList Services  { get; set; }      
    }
}

DevCard_Mvc/Models/ErrorViewModel.cs
using System;

namespace DevCard_Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DevCard_Mvc/Models/IndexModel.cs
using System.Collections.Generic;

namespace DevCard_Mvc.Models
{
    public class IndexModel
    {
        public List<Project> Projects { get; set; }
        public List<Article> Articles { get; set; }
    }
}

DevCard_Mvc/Models/Project.cs
namespace DevCard_Mvc.Models
{
	public class Project
	{
		public long  Id { get; set; }
		
		public string Name { get; set; }
		public string Description { get; set; }
		public string Image { get; set; }
		public string Client { get; set; }


		public Project(long id, string name, string description,string image, string client)
		{
			Id = id;
			Name = name;
			Description = description;
			Image = image;
			Client = client;
		}
	}
}

DevCard_Mvc/Models/Service.cs
namespace DevCard_Mvc.Models
{
    public class Service
    {
        public int Id { get; set; }
        public string Name { get; set; }


        public Service(int id, string name)
        {
            Id = id;
            Name = name;
        }
    }
}

DevCard_Mvc/Controllers/HomeController.cs
using System;
using DevCard_Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using DevCard_Mvc.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DevCard_Mvc.Controllers
{
    
   // [Route("/inventory/products")]
   // [Route("/inventory/products/{action}")]
    //localhost:5001/inventory/products/index
    //localhost:5001/inventory/products/contact
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly List<Service> _services = new List<Service>
        {
            new Service(1,"نقره ای"),
            new Service(2,"طلایی "),
            new Service(3,"پلاتین"),
            new Service(4,"الماسی"),
        };

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        //[Route("MyIndex/{name?}/{model?}")]
        // localhost:5001/inventory/products/MyIndex
        public IActionResult Index( string name,string model)
        {
            
            return View();
        }

        public IActionResult ProjectDetails(long id)
        {
            var project = ProjectStore.GetProjectBy(id);
            return View(project);
        }

        //[HttpGet("ContactPage")]
       // [Route("ContactPage")]
       //localhost:5001/inventory/products/ContactPage
        public IActionResult Contact()
        {
            var model = new Contact();
            {
                SelectList Services = new SelectList(_services, "Id", "Name");
            }
	        return View(model);
        }
        //[HttpPost]
        //public JsonResult Contact(IFormCollection form)
        //{
        //    var name = form["name"];
        //    return Json(Ok());
        //}
        [HttpPost]
        public IActionResult Contact(Contact model)
        {
            model.Services = new SelectList(_services, "Id", "Name");
            //if(!ModelState.IsValid==false)
	            if (!ModelState.IsValid)
	            {
		            ViewBag.error = "اطلاعات وارد شده صحیح تیست لظفا دوباره تلاش کتید ";
		            return View(model);
	            }
            // return RedirectToAction("Index");
           ModelState.Clear();
            model = new Contact()
            {
	            Services = new SelectList(_services, "Id", "Name")
			};
           
            
            ViewBag.success = "پیغام شما با موفقیت ارسال شد با تشکر";
            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DevCard_Mvc/ViewComponents/LatestArticlesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using DevCard_Mvc.Models;



namespace DevCard_Mvc.ViewComponents
{
	public class LatestArticlesViewComponent:ViewComponent
	{
		public IViewComponentResult Invoke()
		{

			var articles = new List<Article>()
			{
				new Article(1,"آموزش Asp.net Core mvc","کاملترین پکیج آموزشasp.net cor mvc","blog-post-thumb-1.jpg"),
				new Article(2," Git and GitHubآموزش Asp.net Core mvc","کاملترین پکیج آموزشasp.net cor mvc","blog-post-thumb-2.jpg"),
				new Article(3,"آموزش Onion Architecture","کاملترین پکیج آموزشasp.net cor mvc","blog-post-thumb-3.jpg"),
				new Article(4,"آموزش طراحی سایت","کاملترین پکیج آموزشasp.net cor mvc","blog-post-thumb-4.jpg")



			};
			return View("_latestArticles", articles);
		}

	}
}

DevCard_Mvc/ViewComponents/ProjectsViewComponent.cs
using System.Collections.Generic;
using DevCard_Mvc.Data;
using DevCard_Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Project = DevCard_Mvc.Models.Project;


namespace DevCard_Mvc.ViewComponents
{
	public class ProjectsViewComponent:ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			//var projects = new List<Project>
			//{
			//	new Project(1, "تاکسی", "درخواست آنلاین تاکسی برای سفرهای درون شهری","project-1.jpg" ,"Atriya"),
			//	new Project(2, "زود فود", "درخواست آنلاین غذا برای سراسر کشور","project-2.jpg", "ZoodFood"),
			//	new Project(3, "مدارس", "سیستم مدیریت یک پارچه", "project-3.jpg","Monop"),
			//	new Project(4, "فضا پیما", "درخواست آنلاین تاکسی برای سفرهای درون شهری", "project-4.jpg","nasa"),
			//};
            var projects = ProjectStore.GetProjects();
			return View("_Projects",projects);
		}
	}


}

DevCard_Mvc/Views/Home/Components/Projects/_Projects.cshtml
@model IEnumerable<DevCard_Mvc.Models.Project>

<section class="featured-section p-3 p-lg-5">
	<div class="container">
		<h2 class="section-title font-weight-bold mb-5">خاص ترین پروژه ها</h2>
        <div class="row">
            @foreach (var project in Model)
            {
                <div class="col-md-6 mb-5">
                    <div class="card project-card">
                        <div class="row no-gutters">
                            <div class="col-lg-4 card-img-holder">
                                <img src="~/assets/images/project/@project.Image" class="card-img" alt="@project.Name" title="@project.Description">
                            </div>
                            <div class="col-lg-8">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <a asp-controller="Home" asp-action="ProjectDetails" asp-route-id="@project.Id" class="theme-link">
                                           @project.Id: @project.Name
                                        </a>
                                    </h5>
                                    <p class="card-text">
                                        @project.Description
                                    </p>
                                    <p class="card-text"><small class="text-muted">مشتری: @project.Client</small></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
         

        </div>
	</div>
</section>

DevCard_Mvc/Views/Home/Contact.cshtml
@model Contact
@{
    ViewData["Title"] = "ارتباط با ما";
}

<section class="cta-section theme-bg-light py-5">
    <div class="container text-center single-col-max-width">
    </div>
	</section>
<section class="contact-section px-3 py-5 p-md-5">
    <div class="container">
        @if (!string.IsNullOrWhiteSpace(ViewBag.success))
        {
            <div class="alert-success p-lg-0" >
                <p>@ViewBag.success"]</p>
            </div>
        }
        
        @if (!string.IsNullOrWhiteSpace(ViewBag.error))
        {
            <div class="alert-danger p-5" >
                <p>@ViewBag.error"]</p>
            </div>
        }
        

       
        <form id="contact-form" class="contact-form col-lg-8 mx-lg-auto" method="post" asp-action="Contact" asp-controller="Home">
            <h3 class="text-center mb-3">در دسترس باشید!</h3>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="sr-only" asp-for="Name">نام</label>
                    <input type="text" class="form-control" asp-for="Name" placeholder="نام">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label class="sr-only" asp-for="Email">ایمیل</label>
                    <input type="email" class="form-control" asp-for="Email" placeholder="ایمیل">
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group col-12">
                    <select class="custom-select" asp-for="Service" asp-items="Model.Services">
                        <option  selected="selected" value="0">سرویس مورد نظر خود را انتخاب کنید...</option>
                        @*<option value="basic">نقره ای</option>
						<option value="standard">طلایی</option>
						<option value="premium">پلاتین</option>
						<option value="not sure">الماس</option>*@
                    </select>
                </div>
                <div class="form-group col-12">
                    <label class="sr-only" asp-for="Message">پیغام شما</label>
                    <textarea class="form-control" asp-for="Message"
							  placeholder="پیغام خود را وارد نمایید ..." rows="10" required=""
							  aria-required="true"></textarea>
                </div>
                <div class="form-group col-12">
                    <button type="submit" class="btn btn-block btn-primary py-2">ارسال</button>
                </div>
            </div>
        </form>
    </div>
</section>

DevCard_Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "صفحه اصلی";
}


<section class="about-me-section p-3 p-lg-5 theme-bg-light">
	<div class="container">
		<div class="profile-teaser media flex-column flex-lg-row">
			<img class="profile-image mb-3 mb-lg-0 ml-lg-5 mr-md-0" src="assets/images/img/IMG-2137.jpg" alt="">
			<div class="media-body">
				<h2 class="name font-weight-bold mb-1">صهبا کاویی</h2>
				<div class="tagline mb-3">برنامه نویس </div>
                <div class="bio mb-4">
                    مهارتهای تخصص ی
                    •
                    •
                    Asp.netCore,Git ,MVC, VB.Net, C#, ASP.NET
                    Scripting Languages: CSS, JavaScript, HTML5, AJAX
                    Databases: MS SQL Server, Oracle •
                    Network: DHCP, DNS, Routing, TCP/IP, Active Directory, IIS •
                    Operating Systems: Windows 10, 8, 7, Vista, XP, Windows Server •
                    General Domain Knowledge: Finance, Inventory, Office Automation, Contract Management •
                    
                </div>
                <h1 class="mc-text-h1 mc-my-2">Full stack Developer</h1>
                <div></div>
                <div> <span style="box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%">
                    <span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%">
                        <img style="display:block;max-width:100%;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0" alt="" aria-hidden="true" src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%27789%27%20height=%27338%27/%3e">
                    </span><img alt="" image="[object Object]" srcset="https://images.ctfassets.net/3s5io6mnxfqz/3rQuOkEHnoPYw88NkubDKs/08ee7bf9c6f2a3d08be45d887e2259b0/AdobeStock_118776815.jpeg?w=828 1x, https://images.ctfassets.net/3s5io6mnxfqz/3rQuOkEHnoPYw88NkubDKs/08ee7bf9c6f2a3d08be45d887e2259b0/AdobeStock_118776815.jpeg?w=1920 2x" src="https://images.ctfassets.net/3s5io6mnxfqz/3rQuOkEHnoPYw88NkubDKs/08ee7bf9c6f2a3d08be45d887e2259b0/AdobeStock_118776815.jpeg?w=1920" decoding="async" data-nimg="intrinsic" class="mc-tile-image" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%">
                </span>
                ></div>
				<div class="mb-4">
					<a class="btn btn-primary mr-2 mb-3" href="http://www.google.com">
						<i class="fas fa-arrow-alt-circle-right ml-2"></i><span class="d-none d-md-inline">
							برو
							به
						</span> گوگل
					</a>
					<a class="btn btn-secondary mb-3" href="#">
						<i class="fas fa-file-alt ml-2"></i>
                        <span class="d-none d-md-inline">مشاهده </span> نمونه کارها
                    </a>
                </div>
            </div>

        </div>
    </div>
</section>

@*<partial name="Projects"/>*@
@*@await Html.PartialAsync(partialViewName:"Projects",new List<Project>())*@
@*// loading view component*@
@await Component.InvokeAsync("Projects")


<div class="container">
    <hr>
</div>


@await Component.InvokeAsync("LatestArticles")

DevCard_Mvc/Views/Home/ProjectDetails.cshtml
@model Project
@{
    ViewData["Title"] = "جزییات پروژه";
}

<section class="cta-section theme-bg-light py-5">
    <div class="container text-center single-col-max-width">
        <h2 class="heading">ارتباط با ما</h2>
        <div class="intro">
            <p>
                شما می توانید از طریق فرم زیر با ما ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
                نوشته و ارسال کنید.
            </p>
            <p>از طریق شبکه های اجتماعی با ما در ارتباط باشید</p>
            <ul class="list-inline mb-0">
                <li class="list-inline-item mb-3">
                    <a class="twitter" href="#">
                        <i class="fab fa-twitter fa-fw fa-lg"></i>
                    </a>
                </li>

                <li class="list-inline-item mb-3">
                    <a class="linkedin" href="#">
                        <i class="fab fa-linkedin-in fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="github" href="#">
                        <i class="fab fa-github-alt fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="instagram" href="#">
                        <i class="fab fa-instagram fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="stack-overflow" href="#">
                        <i class="fab fa-stack-overflow fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="medium" href="#">
                        <i class="fab fa-medium-m fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="codepen" href="#">
                        <i class="fab fa-codepen fa-fw fa-lg"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>

</section>
<section class="contact-section px-3 py-5 p-md-5">
    <div class="container">

        <table class="table  table-bordered table-hover">
            <thead>
            <tr>
                <td>Id</td>
                <td>Name</td>
                <td>Description</td>
                <td>Client</td>
                
            </tr>
            </thead>
            <tbody>
            
            <tr>
                <td>@Model.Id</td>
                <td>@Model.Name</td>
                <td>@Model.Description</td>
                <td>@Model.Client</td>

            </tr>
            </tbody>
            
            
            
            
        </table>

    </div>
</section>

DevCard_Mvc/Views/Shared/Components/LatestArticles/_LatestArticles.cshtml
@model List<Article>


<section class="latest-blog-section p-3 p-lg-5">
	<div class="container">
		<h2 class="section-title font-weight-bold mb-5">آخرین مقالات</h2>
        <div class="row">
            @foreach (var article in Model)
            {
                <div class="col-md-4 mb-5">
                    <div class="card blog-post-card">
                        <img class="card-img-top" src="~/assets/images/blog/@article.Image" alt="@article.Title",title="@article.Description">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a class="theme-link" href="blog-post.html">
                                   @article.Title
                                </a>
                            </h5>
                            <p class="card-text">
                               @article.Description
                            </p>
                            <p class="mb-0"><a class="more-link" href="#">ادامه مطلب</a></p>

                        </div>
                    </div>
                </div>

            }
           

        </div>
	</div>
</section>

DevCard_Mvc/Views/Shared/Header.cshtml
<header class="header text-center">
    <div class="force-overflow">
        <h1 class="blog-name pt-lg-4 mb-0"><a href="index.html">صهبا کاویی</a></h1>

        <nav class="navbar navbar-expand-lg navbar-dark">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navigation" class="collapse navbar-collapse flex-column">
                <div class="profile-section pt-3 pt-lg-0">
                    <img class="profile-image mb-3 rounded-circle mx-auto" src="~/assets/images/img/IMG-2137.jpg" alt="image">

                    <div class="bio mb-3">
                        سلام، صهبا کاویی  هستم . به وبسایت شخصی من خوش
                        آمدید.
                    </div>
                    <ul class="social-list list-inline py-2 mx-auto">
                        <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
                        <li class="list-inline-item">
                            <a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
                    </ul>
                    <hr>
                </div>
                <ul class="navbar-nav flex-column text-right">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index",controller:"Home")">
                            <i class="fas fa-user fa-fw ml-2"></i>صفحه اصلی<span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Contact">
                            <i class="fas fa-envelope-open-text fa-fw ml-2"></i>ارتباط با ما
                        </a>
                    </li>
                </ul>
            </div>
		
        </nav>
    </div>
</header>

DevCard_Mvc/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Routing
@using DevCard_Mvc.Controllers
<!DOCTYPE html>
<html lang="fa">

<head>
	<title>DevCard از sahba kavei</title>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="shortcut icon" href="favicon.ico">

	<script defer src="~/assets/fontawesome/js/all.js"></script>
	<link  rel="stylesheet" href="~/assets/css/theme-1.css">
	<link  rel="stylesheet" href="~/assets/css/style.css">

</head>

<body>

<partial name="Header"/>

<div class="main-wrapper">
		
    @RenderBody()	

    <partial name="footer"/>

</div>

<!-- Javascript -->
<script src="~/assets/plugins/jquery-3.4.1.min.js"></script>
<script src="~/assets/plugins/popper.min.js"></script>
<script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
@*<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>*@
</body>


</html>

DevCard_Mvc/Views/Shared/footer.cshtml
<footer class="footer text-center py-4">
    <small class="copyright">
        
        تولید شده &copy; <a href="http://www.google.com" target="_blank">
            
            توسط kavei Developer
            
        </a>
    </small>
</footer>